# Setup
title:        The Sun In A Sphere
tagline:      Instruction for DIY Sphere of the Sun
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Mischa Nüesch, Lukas Musy
  url:        https://sun-in-a-sphere.github.io/ 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown

show_downloads: ["false"]

